### ISSUE TITLE
Scraper available?

### ISSUE THREAD

**Issue by fleimgruber** [ginseng666/Nationalratsabgeordnete-MPs-Austria-1920-2017#2]
Is the scraper hosted somewhere publicly as well?

**Comment by ginseng666** [comment]
sorry, the code is very raw and i don't feel comfortable uploading it

**Comment by fleimgruber** [comment]
This is somewhat understandable.  It could be fixed or rewritten from scratch, though.  The rationale for asking is the obsession to have both raw data and transformation scripts available for reproducibility and transparency.
